version: '3.8'

services:
  dxf-analyzer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
      - ./reports:/app/reports
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped

  # 추가 서비스 (향후 확장용)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: dxf_analyzer
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
